image: "rust:latest"

stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git

build:linux:
  stage: build
  before_script:
    - add-apt-repository ppa:glasen/freetype2
    - apt-get update && apt-get -y install cmake freetype2-demos
  script:
    - cargo build
  cache:
    paths:
      - cargo/
      - target/

build:web:
  stage: build
  before_script:
    - cargo install --force cargo-web
  script:
    - cargo web build
  cache:
    paths:
      - cargo/
      - target/

#build:redox:
#  stage: build
#  variables:
#        TARGET: x86_64-unknown-redox
#  script:
#    - redoxer build --verbose
#  cache:
#    paths:
#      - cargo/
#      - target/

test:linux:
  stage: test
  before_script:
    - apt-get update && apt-get -y install cmake
    - apt-get install libsdl2-dev -y
  dependencies:
    - build:linux
  script:
    - rustup default nightly
    - cargo test
