[package]
name = "orbtk"
version = "0.3.0"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]
edition = "2018"

[lib]
name = "orbtk"
path = "src/lib.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
orbgl = { git = "https://gitlab.redox-os.org/redox-os/orbgl.git" }
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git" }
orbimage = "0.1.17"
orbclient = "0.3.22"

[dependencies]
orbtk-css-engine = { version = "0.1.0", path = "crates/css-engine" }
orbtk-shell = { version = "0.1.0", path = "crates/shell" }
orbtk-theme = { version = "0.1.0", path="crates/theme" }
orbtk-utils = { version = "0.1.0", path = "crates/utils" }
orbtk-tree = { version = "0.1.0", path="crates/tree" }
lazy_static = "1.3.0"
# dces = { path = "../dces-rust"}
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git" }
# orbgl_api = { path = "../orbgl/orbgl_api" }
orbgl_api = { git = "https://gitlab.redox-os.org/redox-os/orbgl.git" }
# orbgl = { path = "../orbgl/orbgl" }

[features]
debug = []

[workspace]
members = [
    "crates/css-engine",
    "crates/shell",
    "crates/theme",
    "crates/utils",
    "crates/tree"
]