[package]
name = "orbtk-render"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "2D Render library use by OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
license = "MIT"
keywords = ["2D", "render", "canvas"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.18"

[target.'cfg(target_os = "redox")'.dependencies]
orbclient = { version = "0.3.27", optional = true }
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git", optional = true }
orbgl = { git = "https://gitlab.redox-os.org/redox-os/orbgl.git", optional = true }
orbgl_api = { git = "https://gitlab.redox-os.org/redox-os/orbgl.git", optional = true }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
raqote = "0.7.0"
rusttype = "0.7.0"
font-kit = "0.4.0"
euclid = "0.20.1"
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = "0.22.2"

[dependencies]
orbtk-utils = { version = "0.1.0", path = "../utils" }

[features]
default = []