[package]
name = "orbtk-shell"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.18"

[target.'cfg(redox)'.dependencies]
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git", optional = true }
orbclient = { version = "0.3.27", optional = true }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
minifb = "0.13"

[dependencies]
orbtk-render = { version = "0.1.0", path = "../render" }
orbtk-utils = { version = "0.1.0", path = "../utils" }
lazy_static = "1.4.0"