[package]
name = "orbtk-windows"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "OrbTk Window Abstraction Layer."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
license = "MIT"
keywords = ["windowing"]
edition = "2018"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
orbclient = "0.3.9"

[features]
default = []

