[package]
name = "orbtk-api"
version = "0.3.1-alpha2"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "API crate that provides base api and elements for OrbTk like widgets basis."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "api"]
edition = "2018"

[dependencies]
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git" }
orbtk-utils = { path = "../utils", version = "0.3.1-alpha2" }
orbtk-tree = { path = "../tree", version = "0.3.1-alpha2" }
orbtk-css-engine = { path = "../css-engine", version = "0.3.1-alpha2" }
orbtk-render = { path = "../render", version = "0.3.1-alpha2" }
orbtk-shell = { path = "../shell", version = "0.3.1-alpha2" }
orbtk-theme = { path = "../theme", version = "0.3.1-alpha2" }

[features]
debug = []