name: build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build: 
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
      
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      
  build_redox:
    name: Build on Redox OS
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions-rs/components-nightly@v1
      - name: Install redoxer
        run: cargo install redoxer
      - name: Install redoxer toolchain
        run: redoxer install
      - name: Build
        run: redoxer build
           
  build_macos:
    name: Build on macOS
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install rust
        run: brew install rust
      - name: Build
        run: cargo build --verbose
